# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
  batch: true
  branches:
    include:
    - master
    - develop
    - release/*


pool:
  vmImage: windows-latest

steps:
      - task: DotNetCoreCLI@2
        inputs:
          command: 'build'
          projects: '**/*.csproj'
          arguments: '--output $(Build.BinariesDirectory)/publish_output --configuration Release'
      - task: NuGetCommand@2
        displayName: 'Restore NuGet packages'
        inputs:
          command: 'restore'
          restoreSolution: '**/*.sln'
          feedsToUse: 'select'
          vstsFeed: '$(System.TeamProject)/logic_app'
      
      - task: ArchiveFiles@2
        inputs:
             rootFolderOrFile: '$(Build.BinariesDirectory)/publish_output'
             includeRootFolder: false
             archiveType: 'zip'
             archiveFile: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'
             replaceExistingArchive: true
      - task: PublishBuildArtifacts@1
        inputs:
          PathtoPublish: '$(Build.ArtifactStagingDirectory)'
          ArtifactName: 'drop'
          publishLocation: 'Container'
      - task: UniversalPackages@0
        displayName: 'Publish to Azure Artifacts'
        inputs:
          command: 'publish'
          publishDirectory: '$(Build.ArtifactStagingDirectory)'
          feedsToUsePublish: 'internal'
          vstsFeedPublish: '$(System.TeamProject)/logic-app'
          vstsFeedPackagePublish: 'nb_virtocommerce_webhook'
          versionOption: 'custom'
          versionPublish: '$(VCbuild.version)'
          verbosity: 'Warning'

