# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
  batch: true
  branches:
    include:
    - master
    - develop
    - release/*

pool:
  vmImage: windows-latest

steps:
      - task: UseDotNet@2
        inputs:
          version: '3.1.x'
          packageType: sdk

      - task: VSBuild@1
        inputs:
          solution: '**\*.sln'

      - task: PublishBuildArtifacts@1
        inputs:
          targetPath: '$(Pipeline.Workspace)\s\artifacts'
              