# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
  batch: true
  branches:
    include:
    - master
    - develop
    - release/*

pool:
  vmImage: windows-latest

steps:
      - task: VSBuild@1
        inputs:
          solution: '**\*.sln'

      - task: PublishBuildArtifacts@1
        inputs:
          PathtoPublish: '$(Build.ArtifactStagingDirectory)'
          ArtifactName: 'drop'
          publishLocation: 'Container'
              
      - task: AzureFunctionApp@1
        inputs:
           azureSubscription: 'Azure for Students (826da009-e421-40bc-9bc5-1830e205a5c3)'
           appType: 'functionApp'
           appName: 'asfs'
           deployToSlotOrASE: true
           resourceGroupName: 'blob'
           slotName: 'production'
           package: '$(System.DefaultWorkingDirectory)/**/*.zip'
           deploymentMethod: 'auto'