# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
  batch: true
  branches:
    include:
    - master
    - develop
    - release/*


pool:
  vmImage: windows-latest

steps:
      - task: DotNetCoreCLI@2
        inputs:
          command: 'build'
          projects: '**/*.csproj'
          arguments: '--output $(Build.BinariesDirectory)/publish_output --configuration Release'
      - task: ArchiveFiles@2
        inputs:
             rootFolderOrFile: '$(Build.BinariesDirectory)/publish_output'
             includeRootFolder: false
             archiveType: 'zip'
             archiveFile: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'
             replaceExistingArchive: true
      - task: PublishBuildArtifacts@1
        inputs:
          TargetPath: '$(Pipeline.Workspace)\s\artifacts'
          ArtifactName: 'drop'
          publishLocation: 'Container'
      - task: PublishPipelineArtifact@1
        inputs:
          targetPath: '$(Pipeline.Workspace)'
          artifact: 'fucntion app'
          publishLocation: 'pipeline'    